### ISSUE TITLE
Considerar número de sensores

### ISSUE THREAD

**Issue by JoseMaria97IDVIA** [mgonzalez-94/NExT-ERA#2]
Sería interesante considerar cuántos sensores tiene el registro en función del nombre del archivo que se le pasa y número de columnas que posee. 

El número de columnas te dice cuántos sensores hay.
El nombre del archivo cuántos de esos sensores tienen realmente datos.

Mediante un switch se pueden considerar todos los casos y adaptar la matriz que contiene los datos, evitando que haya columnas de ceros.

**Comment by mgonzalez-94** [comment]
> Sería interesante considerar cuántos sensores tiene el registro en función del nombre del archivo que se le pasa y número de columnas que posee.
> 
> El número de columnas te dice cuántos sensores hay.
> El nombre del archivo cuántos de esos sensores tienen realmente datos.
> 
> Mediante un switch se pueden considerar todos los casos y adaptar la matriz que contiene los datos, evitando que haya columnas de ceros.

El código NExT-ERA no tiene problema con que alguna de las columnas sea cero, a menos que se seleccione como canal de referencia.

Pensando en comparar los modos identificados a partir de distintos archivos. Se debería indicar el registro de entrada a NExT-ERA qué canales tiene, para poder comparar luego los resultados de distintos registros. Por ejemplo, si se hace la primera identificación con un registro "..._013" y luego con uno "..._012".

Ya implementado en la última versión.
